import React from 'react'

const Spinner = () => {
  return (
      <div className='spinner'>
      <h1>SPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNERSPINNER</h1>

      </div>
  )
}

export default Spinner